name: cd-prod
on:
  push: { branches: [main] }
  workflow_dispatch: {}

concurrency:
  group: deploy-prod
  cancel-in-progress: true

permissions:
  contents: read
  id-token: write
  deployments: write

env:
  NAMESPACE: ecommerce
  IMAGE_FRONTEND: ecommerce-frontend
  IMAGE_BACKEND:  ecommerce-backend

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4
      - uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Get AKS credentials
        run: az aks get-credentials -g "${{ vars.AKS_RG }}" -n "${{ vars.AKS_NAME }}" --overwrite-existing
      - name: Rollout images
        run: |
          kubectl -n $NAMESPACE set image deploy/frontend frontend=${{ vars.ACR_LOGIN_SERVER }}/$IMAGE_FRONTEND:${{ github.sha }}
          kubectl -n $NAMESPACE set image deploy/backend  backend=${{ vars.ACR_LOGIN_SERVER }}/$IMAGE_BACKEND:${{ github.sha }}
          kubectl -n $NAMESPACE rollout status deploy/frontend --timeout=180s
          kubectl -n $NAMESPACE rollout status deploy/backend  --timeout=180s
