name: CD

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Setup kubeconfig from secret
      - name: Set up KUBECONFIG
        run: |
          echo "${{ secrets.KUBE_CONFIG_B64 }}" | base64 -d > kubeconfig.yaml
          export KUBECONFIG=$PWD/kubeconfig.yaml
          kubectl config view --minify

      # Verify connection to AKS
      - name: Verify cluster
        run: kubectl get nodes

      # Deploy manifests to AKS
      - name: Deploy to AKS
        run: |
          kubectl apply -f k8s/
          kubectl rollout status deploy/frontend -n shop --timeout=180s || true
          kubectl rollout status deploy/backend -n shop --timeout=180s || true
