name: CI – Build & Push (backend + frontend)

on:
  push:
    branches: [ dev, main ]
    paths:
      - 'backend/**'
      - 'frontend/**'
      - 'k8s/**'
      - '.github/workflows/**'
  pull_request:
    branches: [ dev, main ]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

env:
  ACR_LOGIN_SERVER: ${{ secrets.ACR_LOGIN_SERVER }}
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Azure Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build & Push Backend
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          push: true
          tags: |
            ${{ env.ACR_LOGIN_SERVER }}/backend:${{ env.IMAGE_TAG }}
            ${{ env.ACR_LOGIN_SERVER }}/backend:latest
          cache-from: type=registry,ref=${{ env.ACR_LOGIN_SERVER }}/backend:buildcache
          cache-to: type=registry,ref=${{ env.ACR_LOGIN_SERVER }}/backend:buildcache,mode=max

  build-frontend:
    runs-on: ubuntu-latest
    needs: build-backend
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Azure Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build & Push Frontend
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          push: true
          tags: |
            ${{ env.ACR_LOGIN_SERVER }}/frontend:${{ env.IMAGE_TAG }}
            ${{ env.ACR_LOGIN_SERVER }}/frontend:latest
          cache-from: type=registry,ref=${{ env.ACR_LOGIN_SERVER }}/frontend:buildcache
          cache-to: type=registry,ref=${{ env.ACR_LOGIN_SERVER }}/frontend:buildcache,mode=max
