name: build-and-push
on:
  workflow_call:
    inputs:
      service: { required: true, type: string }
      context: { required: true, type: string }
      image:   { required: true, type: string }

permissions:
  contents: read

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: '20' }

      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: ${{ inputs.context }}/node_modules
          key: ${{ runner.os }}-${{ inputs.service }}-${{ hashFiles(format('{0}/package-lock.json', inputs.context)) }}

      - name: Build image
        run: docker build -t ${{ inputs.image }}:${{ github.sha }} ${{ inputs.context }}

      - name: Azure login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Push to ACR
        env:
          ACR_LOGIN_SERVER: ${{ vars.ACR_LOGIN_SERVER }}
        run: |
          az acr login --name "${ACR_LOGIN_SERVER%%.*}"
          docker tag ${{ inputs.image }}:${{ github.sha }} $ACR_LOGIN_SERVER/${{ inputs.image }}:${{ github.sha }}
          docker push $ACR_LOGIN_SERVER/${{ inputs.image }}:${{ github.sha }}
